//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmnPardaz.Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class APDatabaseEntities : DbContext
    {
        public APDatabaseEntities()
            : base("name=APDatabaseEntities")
        {
            Database.SetInitializer(new CreateDatabaseIfNotExists<APDatabaseEntities>());
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Courses>().HasKey(c => c.CourseId);
            modelBuilder.Entity<DayWeek>().HasKey(d => d.DayId);
            modelBuilder.Entity<Times>().HasKey(d => d.TimeId);
            modelBuilder.Entity<Users>().HasKey(d => d.UserId);
            modelBuilder.Entity<UserWeek>().HasKey(d => d.UWID);
        }

        public virtual DbSet<Courses> Courses { get; set; }
        public virtual DbSet<DayWeek> DayWeek { get; set; }
        public virtual DbSet<Times> Times { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UserWeek> UserWeek { get; set; }
    }
}
